error = {
	    Track_700_errorCode : "Track_700",
		Track_700_errorMessage : "",
		Track_701_errorCode : "Track_701",
		Track_701_errorMessage : "Invalid Country Code",
		Track_702_errorCode : "Track_702",
		Track_702_errorMessage : "Invalid Mobile Number",
		Track_703_errorCode : "Track_703",
		Track_703_errorMessage : "Authentication fail",
		Track_704_errorCode : "Track_704",
		Track_704_errorMessage : "Expired OTP",
		Track_705_errorCode : "Track_705",
		Track_705_errorMessage : "Invalid OTP",
		Track_706_errorCode : "Track_706",
		Track_706_errorMessage : "Invalid Member",
		Track_711_errorCode : "Track_711",
		Track_711_errorMessage : "Email was not sent",
        Track_712_errorCode : "Track_712",
		Track_712_errorMessage : "Invalid Registration Id",
        Track_713_errorCode : "Track_713",
		Track_713_errorMessage : "Invalid Registration Id",
        Track_714_errorCode : "Track_714",
		Track_714_errorMessage : "Invalid Registration Id",
        Track_715_errorCode : "Track_715",
		Track_715_errorMessage : "Invalid Registration Id",
        Track_716_errorCode : "Track_716",
		Track_716_errorMessage : "Invalid Registration Id",
        Track_717_errorCode : "Track_717",
		Track_717_errorMessage : "Unable to send Message",
        Track_718_errorCode : "Track_718",
		Track_718_errorMessage : "Unable to send Message",
        Track_719_errorCode : "Track_719",
		Track_719_errorMessage : "Invalid Uiid",
        Track_720_errorCode : "Track_720",
		Track_720_errorMessage : "No such group exist"   		
};
module.exports = error;